1. `values added: 20`
2. `final result: 20`
3. `values added: 20`
4. This will throw an exception because the *let* declaration prevents `result` from being in the scope of the function call on line 13.
5. This will throw an exception because the *const* declaration prevents `result` from being written to on line 7, so this code is never reached.
6. This will throw an exception because the *const* declaration prevents `result` from being written to on line 7, so this code is never reached.